font_family JetBrainsMono Nerd Font
font_size   12
bold_font   auto
italic_font auto
background #1D2D44
background_opacity  0.5
background_blur 20
window_padding_width 0
window_margin_width 0

wayland_titlebar_color  transparent
hide_window_decorations no

enable_audio_bell no

#clipboard sync
clipboard_control write-clipboard write-primary
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

#Copy to select
copy_on_select on

#Tab Bar 
tab_title_template {title}
tab_bar_style powerline 
tab_bar_edge top
#tab_bar_align centerl
tab_bar_max_length 25
tab_bar_background #1D2D44
active_tab_foreground #0D1321
active_tab_background #F0EBD8
inactive_tab_foreground #1D2D44
inactive_tab_background #0D1321

#Keybinds
#Launch app
map f1 launch_tab nvim
map f2 launch_tab btop
#Tab
map ctrl+tab new_tab
unmap ctrl+shift+t new_tab

map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

resize_in_steps no

# Layouts
enabled_layouts tall:bias=50;full_size=1;mirrored=false

# Startup
startup_session ~/.config/kitty/session.conf
