# Session Manager on Kitty

# Tab 1: shell
new_tab
title shell
launch --cwd ~

# Tab 2: file manager
#new_tab
#title files
#launch --cwd ~/Documents yazi

# Tab 3: dev
new_tab
title nvim
launch --cwd ~/Documents/Projets nvim
